### ISSUE TITLE
Download dirver failed

### ISSUE THREAD

**Issue by sologaxiz** [patjak/bcwc_pcie#117] opened 2017-05-22 12:47 UTC
`uname -a
Linux opium.local 3.10.0-514.16.1.el7.x86_64 #1 SMP Fri Mar 10 13:12:32 EST 2017 x86_64 x86_64 x86_64 GNU/Linux`

```
~/D/b/firmware make

Checking dependencies for driver download...
/usr/bin/curl
/usr/bin/xzcat
/usr/bin/cpio

Downloading the driver, please wait...
mv: cannot stat ‘System/Library/Extensions/AppleCameraInterface.kext/Contents/MacOS/AppleCameraInterface’: No such file or directory
make: *** [AppleCameraInterface] Error 1
```

**Comment by patjak** [comment] 2017-05-22 13:20
Duplicate of issue #115

**Closed by patjak** 2017-05-22 13:20 UTC
