### ISSUE TITLE
Webcam stopped working after summer 2018, MBA6.2.

### ISSUE THREAD

**Issue by UgisL** [patjak/bcwc_pcie#167] opened 2018-11-12 12:15 UTC
Hi,

I am using Arch Linux on Macbook Air 6.2 (mid-2013). Up till recently (I believe around summer year 2018, I do not use webcam too often) the webcam was working nicely, I could use it in web-Skype interface, also Google-hangouts. After some updates (not sure, which one exactly), it has stopped working.

Now it does not work anymore and the symptoms are rather weird:
1) For a moment (could be couple of seconds, could be just a split-second) the video works fine;
2) Then the video freezes and "kworker/1:3+events" constantly runs at 100% CPU, while green lamp next to webcam continues to shine.
3) dmesg output:
[    3.139555] facetimehd: loading out-of-tree module taints kernel.
[    3.139589] facetimehd: module verification failed: signature and/or required key missing - tainting kernel
[    5.424211] facetimehd 0000:02:00.0: Direct firmware load for facetimehd/1871_01XX.dat failed with error -2
4) The only way I have managed to reset the camera is to reboot my comuter.

I have been using the firmware and module from AUR, ([link1](https://aur.archlinux.org/packages/bcwc-pcie-git/), [link2](https://aur.archlinux.org/packages/facetimehd-firmware/)). This issue could be similar as the one here: [#158](https://github.com/patjak/bcwc_pcie/issues/158), judging from the last error I am getting. For me, cheese does not work at all. I am currently on krenel:
4.18.16-arch1-1-ARCH

Any ideas or suggestions? If the issue is with some other software, I would appreciate any directions.

**Comment by patjak** [comment] 2018-12-05 13:46
I observed the same problem with the latest stable kernel (4.19.x). It seems something in V4L2 changed and broke or exposed a bug in the the driver. I need to bisect this to figure out what caused the breakage. Will take a look at it.

**Comment by mmoya** [comment] 2018-12-05 22:18
FWIW, I'm facing this in Arch using 4.9.137-1-lts49.

**Comment by patjak** [comment] 2018-12-06 08:36
That is odd, I would expect an older kernel like that to work.

**Comment by patjak** [comment] 2018-12-18 14:42
I bisected this and found the following merge commit to be the problem. No idea yet how this patch can cause the hang but I re-did the bisect several times with the same result.

commit 3b24b83763e72a6c1e728100104fd99aa83a7b3b (HEAD, refs/bisect/bad)
Merge: 0734e00ef9e4 a95b37e20db9
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Tue Apr 3 15:51:22 2018 -0700

    Merge tag 'kbuild-v4.17' of git://git.kernel.org/pub/scm/linux/kernel/git/masahiroy/linux-kbuild

**Comment by G-Michel** [comment] 2019-02-08 19:37
hi patjak i've the same issue with kernel 4.20 in manjaro. do you have maybe an idea of a workaround for this problem ? thank you !

**Comment by patjak** [comment] 2019-03-17 22:01
Hi all. I just committed a fix for this bug (9190f7d3b8e26179149a90b3d0138e6bc179afab). It was caused by ASPM support starting to work for the device due to improvements in the kernel. I've disabled ASPM for the device in the driver. There might be a better way to handle this through ACPI but this will have to do for now. Please test and report back. Thanks.

**Comment by mmoya** [comment] 2019-03-30 23:55
_master_ is working again in 4.19.32-1-lts (Arch Linux). Thank you!.

Test with Chromium (73.0.3683.86-1). Cheese fails to open the video feed with the following error:
```
$ cheese 

(cheese:3883): cheese-WARNING **: 00:52:15.931: remote error: no more input formats: ../pipewire/src/gst/gstpipewiresrc.c(948): on_remote_state_changed (): /GstCameraBin:camerabin/GstWrapperCameraBinSrc:camera_source/GstBin:bin35/GstPipeWireSrc:pipewiresrc1
```

**Comment by patjak** [comment] 2019-04-01 07:57
@mmoya thanks for testing. The cheese problem seems to be unrelated. Please open a new issue for that. Thanks

**Closed by patjak** 2019-04-01 07:57 UTC
