### ISSUE TITLE
Reverted left & right video

### ISSUE THREAD

**Issue by jbfavre** [patjak/bcwc_pcie#80] opened 2016-05-23 14:55 UTC
Latest driver version works well on my Macbook 12.1.
The only issue is that video is left-right reversed.

- Driver commit: 5a7083b
- Debian kernel: 4.5.4-1 (sid)

**Comment by patjak** [comment] 2016-05-23 21:24
Duplicate of issue #79 ?

**Closed by patjak** 2016-05-23 21:24 UTC
