### ISSUE TITLE
Facetime HD not working in Skype Preview

### ISSUE THREAD

**Issue by arun-gurung** [patjak/bcwc_pcie#145] opened 2017-11-29 16:06 UTC
Report:

Facetime HD works in Cheese and OBS, but not in Skype Preview version 8.11.76.8. 

My Logitech HD Pro Webcam C920 works fine in Skype.

Linux kernel 4.11.

**Comment by wvengen** [comment] 2017-12-28 10:39
This is probably a duplicate of #139 (the Chrome bug), right?

**Comment by estathop** [comment] 2018-04-07 19:42
it is probably the chromium bug, I can confirm the same problem with Skype and Facebook Messenger on FireFox, Ubuntu 17.10 Macbook Air 2015

**Comment by WhyNotHugo** [comment] 2018-04-10 20:09
It's the same bug as older chrome versions. Skype preview is basically a webapp with an older chromium embedded.

**Comment by trackermb** [comment] 2018-12-14 19:44
Hi there I have the same issue the facetime camera (macbook pro 2014) works in cheese and in hangouts, But doesnt work on skype in chrome, firefox or on the app its self.  Is there something I have missed?

**Comment by arun-gurung** [comment] 2018-12-15 06:59
Facetime HD works with Viber on Linux, but still no with "skypeforlinux". Still waiting...

**Closed** 2019-03-20 13:09 UTC
