### ISSUE TITLE
Not working on Ubuntu 18.04+, but working with a fresh install of Debian

### ISSUE THREAD

**Issue by NoMod-Programming** [patjak/bcwc_pcie#170] opened 2018-12-09 00:20 UTC
I've recently switched from Ubuntu 19.04 (having upgrade from 18.04 to 18.10 and then finally to 19.04) to Debian 9.6, and each time except for the last, this driver caused the system to crash fairly quickly (it'd get a few frames out and then I'd get an error along the lines of a CPU "soft lockup" if I checked in dmesg.

After moving to Debian 9.6, though, I installed this driver, tested it out, and it surprisingly worked immediately (except for a reddish tint which may have been due to lighting). Putting the computer to sleep and opening it again also works without issues, and also fixes the red tint issue. My kernel version on Debian is `4.9.135-1`, and my output of lsmod is located [here](https://pastebin.com/gLJf34ZS)

Also interestingly, suspending and then waking up the computer works just fine for me.

**Comment by patjak** [comment] 2019-01-02 08:37
Duplicate of https://github.com/patjak/bcwc_pcie/issues/167

**Closed by patjak** 2019-01-02 08:37 UTC
