### ISSUE TITLE
Can you port the darwin/osx driver?

### ISSUE THREAD

**Issue by SicVolo** [patjak/bcwc_pcie#3] opened 2014-10-01 04:48 UTC
Or may-be just use it as a point of reference in a black-box separation study if licensing is a problem? 
it's in System/Library/Extensions/Apple_iSight.kext/Contents/MacOS/Apple_iSight
There's a bunch of people who need iSight to work, yet non able to write a linux driver.

**Comment by christianbundy** [comment] 2015-03-17 22:29
I believe this issue is ready to be closed now that #7 has been merged.

**Comment by samlauzon** [comment] 2015-07-25 04:02
The decompress app didn't work for me on the latest image, but once you rip the firmware out of the segment, you can use regular g(un)zip to inflate it. 

 The contents of mine: 
Jan 21 2015  16:54:51 -- S2ISP-01.39.00; H4ISPAPPLE H4ISPC ffw iPhone OS 7.0.3

 The way the data is offset, it looks like an ARM64 binary image; Mentions of tasks and semaphores lead me to believe it's some apple in-house RTOS. Both the OV5650 and IMX125 have been used in iPhones, so it's not surprising to think this isn't just something Apple had Broadcom cook up and wrap a PCI-E core around.

 There's also a string about "CDualStreamControllerBase.cpp" and I can confirm the mention of two image sensors that @ddcc noticed. As well as LUX vs LED Flash gain.. (I don't remember a flash on my macbook..)

**Comment by patjak** [comment] 2015-08-01 14:45
@samlauzon 
There are also various references in the driver to S2 which could be the following chip:
http://www.ambarella.com.tw/uploads/docs/S2-ipcam-product-brief.pdf

Will see soon enough since I'm close to powering it up and loading the firmware :)

**Closed** 2015-12-26 23:30 UTC
